# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6eda0fc20659f903a08c171acd468b0d67933869454e7be14cc84a506f49dcb6c7ac126c818cbef1340c857ab45ceac7fad7d267ce4b2e821d1abe87a7733c8

test:
  secret_key_base: 3398aa47515cc9eeb9c0e9c4ac41288dcd2fe51eb421c0857e681ffe1318d8320b412af791f104c36fbaa21706ce8e8dfd2f6f2fc4feafd828ccc2f1c3abf5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
